# Builds developing environment for rumors-api
#
version: '2'
services:
  db:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    ports:
      - "62222:9200"
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
    environment:
      - "path.repo=/usr/share/elasticsearch/data"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Prevent elasticsearch eating up too much memory

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.2
    depends_on:
      - db
    environment:
      ELASTICSEARCH_URL: http://db:9200 # Through docker network, not exposed port
    ports:
      - "6222:5601"

  url-resolver:
    image: johnsonliang/cofacts-url-resolver
    ports:
      - "4000:4000"

  api:
    image: node:carbon@sha256:09cf39a09c227a0c4f8df7b864fb1c32462166669172628f86cb45d87e7aac2f
    container_name: rumors-api
    depends_on:
      - db
    working_dir: "/srv/www"
    entrypoint: npm run dev
    volumes:
      - ".:/srv/www"
    environment:
      ELASTICSEARCH_URL: "http://db:9200"
      URL_RESOLVER_URL: "http://url-resolver:4000"
    ports:
      - "5000:5000"
